version: '3'

services:
  mysql:
    image: mysql:5.7
    container_name: listaDeContatos-DB
    ports:
      - "3306:3306"
    volumes:
      - todo-mysql-data:/var/lib/mysql
    environment: 
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}

volumes:
  todo-mysql-data:
